#!/usr/bin/env bash

function abs_target {
    if [[ ${1} =~ ^https?://.+ ]]; then
        echo $1
    else
        #Generate the absolute path of test script
        cd "$2"
        cd "$(dirname "$1")"
        echo "$(printf "%s/%s\n" "$(pwd)" "$(basename "$1")")" 
    fi
}

#Store the current working directory to return after calculating abspath
ORIGIN_PATH="$(pwd)"

#cd to ExpoSE directory
cd "$(dirname "${BASH_SOURCE[0]}")"

if [[ ${EXPOSE_LOG_LEVEL} && ${EXPOSE_LOG_LEVEL-x} ]]; then
	RECOMPILE="1"
fi

#If the RECOMPILE flag is set then call the recompile script
if [[ ${RECOMPILE} && ${RECOMPILE-x} ]]; then

	./scripts/build/build_all

	if [ $? -ne 0 ]; then
		exit 1
	fi

fi

if [ "$1" == "ui" ]; then #Launch the user interface

    export PATH=$PATH:$(pwd)
    (cd Dashboard && npm start);
	exit $?

elif [ "$1" == "ahg" ]; then

	NODE_PATH="$NODE_PATH:$ORIGIN_PATH/node_modules" EXPOSE_QUERY_DUMP=$EXPOSE_QUERY_DUMP EXPOSE_HARNESS_TARGET=$2 ./scripts/analyse ./lib/Harness/src/harness.js "${@:3}"

elif [ "$1" == "replay" ]; then
	source ./scripts/expose_env
	TARGET_REAL_PATH="$(abs_target $2 $ORIGIN_PATH)"
	./scripts/play $TARGET_REAL_PATH "${@:3}"
	exit $?
else

    if [[ $1 =~ ^http(s)?:// ]]; then #Web URL, launch web mode
        echo "Web Mode, Starting Proxy"
        PID="$(./scripts/run_proxy)"
        sleep 3s
        EXPOSE_PLAY_SCRIPT="./scripts/play_electron"
    fi
   
    #Rewrite the file path (Will not rewrite things prefixed by http/s 
    TARGET_REAL_PATH=$(abs_target "$1" "$ORIGIN_PATH")

    EXPOSE_PLAY_SCRIPT=${EXPOSE_PLAY_SCRIPT} EXPOSE_QUERY_DUMP=$EXPOSE_QUERY_DUMP ./scripts/analyse "$TARGET_REAL_PATH" "${@:2}"
    OUT_CODE=$?

    if [[ ! -z $PID ]]; then
        echo "Killing server"
        kill $PID
    fi
	
    exit $OUT_CODE
fi
