#!/bin/bash

#Store the current working directory to return after calculating abspath
ORIGIN_PATH="$(pwd)"

#If command is setup run setup script and exit
if [ "$1" == "setup" ]; then
	./scripts/setup/setup
	exit $?
fi

./scripts/setup_if_needed

#cd to ExpoSE directory
cd "$(dirname "${BASH_SOURCE[0]}")"

if [ -z ${NO_COMPILE} ]; then
	./scripts/build/build_analyser
	if [ $? -ne 0 ]; then
		exit 1
	fi
fi

if [ "$1" == "ui" ]; then
	NO_COMPILE=1 ./scripts/start_ui
	exit $?
elif [ "$1" == "uic" ]; then
	./scripts/start_ui
	exit $?
elif [ "$1" == "replay" ]; then
	source ./scripts/expose_env

	#Generate the absolute path of test script
	cd "$(dirname "$2")"
	TARGET_REAL_PATH="$(printf "%s/%s\n" "$(pwd)" "$(basename "$2")")"
	cd $ORIGIN_PATH

	./scripts/play $TARGET_REAL_PATH "${@:3}"
	exit $?
elif [ "$1" == "test_suite" ]; then
	./scripts/run_tests
	exit $?
else

	#Generate the absolute path of test script
	cd "$(dirname "$1")"
	TARGET_REAL_PATH="$(printf "%s/%s\n" "$(pwd)" "$(basename "$1")")"
	cd $ORIGIN_PATH

	./scripts/analyse $TARGET_REAL_PATH "${@:2}"
	exit $?
fi