var x = S$.symbol("X", '');
var isIn = /^LOREM IPSUM DIPSUM LOREM IPSUM DIPSUM LOREM IPSUM DIPSUMLOREM IPSUM DIPSUM LOREM IPSUM DIPSUM LOREM IPSUM DIPSUMLOREM IPSUM DIPSUMLOREM IPSUM DIPSUMLOREM IPSUM DIPSUMLOREM IPSUM DIPSUMLOREM IPSUM DIPSUMLOREM IPSUM DIPSUMLOREM IPSUM DIPSUM$/.test(x);

if (isIn) {
	throw 'Reachable';
} else {
	throw 'Reachable';
}