#!/usr/bin/env bash

echo "Setting up for Node"
node --version

echo "Installing pre-commit"
cp ./scripts/pre-push .git/hooks/

echo "Setting Up Packages"
./scripts/setup/setup_packages

touch ~/.bashrc

echo "Installing into PATH"
./scripts/setup/install_bashprofile

./scripts/build/build_analyser

exit 0
