#!/usr/bin/env bash

#Install Node
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
source ~/.nvm/nvm.sh
nvm install 8.12.0
source ~/.nvm/nvm.sh

npm --unsafe-perm install
