#!/usr/bin/env bash

git config --global user.name "Blake Loring"
git config --global user.email "blake@parsed.uk"

#Install Node
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
source ~/.nvm/nvm.sh
nvm install 8.12.0
source ~/.nvm/nvm.sh

npm --unsafe-perm install
