#!/bin/bash
./scripts/build/build_analyser

echo "Spawning proxy"
PID="$(./scripts/run_proxy)"

echo "Proxy PID" $PID
sleep 5s

echo "${@}"

EXPOSE_PLAY_SCRIPT=./scripts/play_electron ./expoSE "${@}"

echo "Kill ${PID}"
kill $PID
echo "Fin"
