#!/usr/bin/env bash

unset RECOMPILE

./scripts/build/build_all
./scripts/build/build_tester

if [ $? -ne 0 ]; then
	exit 1
fi

node --version
node ./Tester/bin/TestRunner.js ./tests/ test_list

exit $?
