#!/usr/bin/env bash
grep -q '\/\*.*(c).*\*\/' $1 || echo "/* Copyright (c) Royal Holloway, University of London | Contact Blake Loring (blake@parsed.uk) or Johannes Kinder (johannes.kinder@rhul.ac.uk) for details or support | LICENSE.md for license details */

$(cat $1)" > $1
