#!/bin/bash

#Store the current working directory to return after calculating abspath
ORIGIN_PATH="$(pwd)"

#Generate the absolute path of test script as it will be lost on cd into Tropigate
cd "$(dirname "$1")"
TARGET_REAL_PATH="$(printf "%s/%s\n" "$(pwd)" "$(basename "$1")")"
OUT_REAL_PATH="$(printf "%s/%s\n" "$(pwd)" "$(basename "$2")")"

#cd to Tropigate directory
cd $ORIGIN_PATH
cd "$(dirname "${BASH_SOURCE[0]}")"

if [ -z ${NO_COMPILE} ]; then
	./build_tropigate
fi

if [ -z ${2} ]; then
	./run_tropigate $TARGET_REAL_PATH
else
	./run_tropigate $TARGET_REAL_PATH > $OUT_REAL_PATH
fi